#
# REF:
#   1. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrixinclude
#
name: Create Release Draft

on:
  workflow_dispatch:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+*']

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
        extra: ['bin']
        include:
          - target: x86_64-pc-windows-msvc
            extra: 'bin'
            os: windows-latest
            target_rustflags: ''

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - name: Update Rust Toolchain Target
        run: |
          echo "targets = ['${{matrix.target}}']" >> rust-toolchain.toml

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          rustflags: ''

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3
        with:
          version: 0.81.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Nu Binary
        id: nu
        run: nu .github/workflows/release-pkg.nu
        env:
          OS: ${{ matrix.os }}
          REF: ${{ github.ref }}
          TARGET: ${{ matrix.target }}
          _EXTRA_: ${{ matrix.extra }}
          TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}

      - name: Upload APK x86_64
        uses: actions/upload-artifact@v2.3.1
        with:
          name: nushell.zip
          path: ${{ steps.nu.outputs.archive }}
